---
title: "ggstackplot examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ggstackplot examples}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(dplyr)
library(ggplot2)
library(ggstackplot)
```

# Example 1: high altitude balloon flight

## Load example data

The data in this example are from measurements acquired on a scientific high altitude balloon flight. Caro, T.A., Wendeln, M., Freeland, M. et al. Ultraviolet light measurements (280–400 nm) acquired from stratospheric balloon flight to assess influence on bioaerosols. Aerobiologia 35, 771–776 (2019). https://doi.org/10.1007/s10453-019-09597-9

```{r}
hab_data <- readRDS("HAB_example_data.RDS") |>
  slice_head(n = 100)

head(hab_data)
```

## Visualize example data

```{r, fig.height=8, fig.width=7}
hab_data |> 
  ggstackplot(
    x = `alt (m)`,
    y = c(`Temperature (C)`, `Pressure (hPa)`, `Speed (m/s)` = `speed`, `Total UV Flux (mW/cm)`),
    color = c("darkblue", "darkgreen", "black", "red"),
    alternate_axes = TRUE,
    switch_axes = TRUE,
    shared_axis_size = 0.3,
    overlap = 0.1,
    template =
      ggplot() +
      scale_x_continuous(
        name = "Altitude (m)",
        n.breaks = 12,
        sec.axis = sec_axis(
          name = "Altitude (km)",
          trans = ~ . / 1000
        ),
        expand = c(0, 0)
      ) +
      expand_limits(x = 0) +
      geom_rect(ymin = -Inf, ymax = Inf,
                xmin = 0, xmax = 7500,
                fill = "lightgray", color = NA,
                alpha = 0.1) +
      geom_rect(ymin = -Inf, ymax = Inf,
                xmin = 7500, xmax = 35000,
                fill = "lightblue1", color = NA,
                alpha = 0.1) +
      theme_stackplot(),
    add = list(
      `Temperature (C)` = geom_path(),
      `Pressure (hPa)` = 
        geom_path() +
        theme(axis.text.x = element_text(angle = 45, hjust = 0)),
      `Speed (m/s)` = geom_path(),
      `Total UV Flux (mW/cm)` = 
        scale_y_continuous(limits = c(0, 10), sec.axis = dup_axis()) +
        geom_path() 
    )
  )
```

